// apps/web-next/components/Navbar.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { usePrivy } from "@privy-io/react-auth";
import { nearService } from "@/lib/services/near";
import { useNear } from "@/hooks/useNear";

function formatNearBalance(balance: string | null): string {
    if (!balance) return "N/A";

    const value = Number(balance);
    if (!Number.isFinite(value)) return `${balance} NEAR`;
    if (value >= 1) return `${value.toFixed(2)} NEAR`;
    return `${value.toFixed(4)} NEAR`;
}

export default function Navbar() {
    const { login, authenticated, user, logout } = usePrivy();
    const { accountId, isConnected } = useNear();
    const [nearBalance, setNearBalance] = useState<string | null>(null);
    const [isBalanceLoading, setIsBalanceLoading] = useState(false);

    const loadNearBalance = useCallback(async () => {
        if (!authenticated || !isConnected || !accountId) {
            setNearBalance(null);
            setIsBalanceLoading(false);
            return;
        }

        setIsBalanceLoading(true);
        try {
            const { near } = await nearService.getNativeBalance(accountId);
            setNearBalance(near);
        } catch (error) {
            console.error("Navbar: Failed to load NEAR balance", error);
            setNearBalance(null);
        } finally {
            setIsBalanceLoading(false);
        }
    }, [authenticated, isConnected, accountId]);

    useEffect(() => {
        void loadNearBalance();
    }, [loadNearBalance]);

    useEffect(() => {
        if (!authenticated || !isConnected || !accountId) return;
        const interval = setInterval(() => {
            void loadNearBalance();
        }, 15000);
        return () => clearInterval(interval);
    }, [authenticated, isConnected, accountId, loadNearBalance]);

    const handleLogin = async () => {
        if (authenticated) {
            await logout();
            await nearService.logout({ silent: true }); // Also clear NEAR service state
        } else {
            login();
        }
    };

    return (
        <nav className="fixed top-0 left-0 right-0 z-50 bg-black/50 backdrop-blur-xl border-b border-white/10">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-16">
                    <div className="flex items-center gap-8">
                        <Link href="/" className="text-xl font-bold text-white">
                            ZK P2P
                        </Link>
                        <div className="hidden md:flex items-center gap-6">
                            <Link href="/buy" className="text-gray-300 hover:text-white transition-colors">Buy</Link>
                            <Link href="/sell" className="text-gray-300 hover:text-white transition-colors">Sell</Link>
                            <Link href="/dashboard" className="text-gray-300 hover:text-white transition-colors">Dashboard</Link>
                        </div>
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            {authenticated && isConnected && (
                                <div className="hidden sm:flex items-center gap-2 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-xs">
                                    <span className="text-gray-400">Balance</span>
                                    <span className="font-mono text-white">
                                        {isBalanceLoading ? "..." : formatNearBalance(nearBalance)}
                                    </span>
                                </div>
                            )}
                            <button
                                type="button"
                                onClick={handleLogin}
                                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors cursor-pointer z-50 relative flex items-center gap-2"
                            >
                                {authenticated ? (
                                    <>
                                        <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></span>
                                        {user?.email?.address || user?.wallet?.address?.slice(0, 6) + "..." || "Connected"}
                                    </>
                                ) : (
                                    "Connect"
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    );
}

// apps/web/src/lib/components/Navbar.svelte
<script lang="ts">
    import { page } from "$app/stores";
    import { nearService, nearStore } from "$lib/services/near";
    import { onMount } from "svelte";

    // Computed properties from NEAR store
    $: authenticated = $nearStore.isConnected;
    $: address = $nearStore.accountId;

    onMount(async () => {
        await nearService.init();
    });

    function handleLogin() {
        nearService.login();
    }
</script>

<nav
    class="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 py-4 backdrop-blur-md bg-black/20 border-b border-white/5"
>
    <!-- Left: Logo -->
    <a href="/" class="flex items-center gap-2 group">
        <div
            class="w-10 h-10 bg-white rounded-xl flex items-center justify-center text-black font-bold text-xl group-hover:scale-105 transition-transform"
        >
            Z
        </div>
        <span class="font-bold text-xl tracking-tight hidden sm:block"
            >ZK P2P</span
        >
    </a>

    <!-- Center: Navigation -->
    <div class="hidden md:flex items-center gap-8">
        <a
            href="/buy"
            class="text-sm font-medium text-gray-400 hover:text-white transition-colors border-b-2 border-transparent hover:border-white/20 pb-1"
            >Buy</a
        >
        <a
            href="/sell"
            class="text-sm font-medium text-gray-400 hover:text-white transition-colors border-b-2 border-transparent hover:border-white/20 pb-1"
            >Sell</a
        >
        <a
            href="/leaderboard"
            class="text-sm font-medium text-gray-400 hover:text-white transition-colors border-b-2 border-transparent hover:border-white/20 pb-1"
            >Leaderboard</a
        >
        <a
            href="/dashboard"
            class="text-sm font-medium text-gray-400 hover:text-white transition-colors border-b-2 border-transparent hover:border-white/20 pb-1"
            >Dashboard</a
        >
    </div>

    <!-- Right: Wallet -->
    <div class="flex items-center">
        {#if authenticated}
            <button
                on:click={() => nearService.logout()}
                class="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/5 px-4 py-2 rounded-full transition-all group"
            >
                <div
                    class="w-2 h-2 rounded-full bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.5)]"
                ></div>
                <span
                    class="text-sm font-medium text-gray-300 group-hover:text-white"
                >
                    {address?.length > 20
                        ? address.slice(0, 15) + "..."
                        : address}
                </span>
            </button>
        {:else}
            <button
                on:click={handleLogin}
                class="btn-primary text-sm py-2 px-6"
            >
                Connect Wallet
            </button>
        {/if}
    </div>
</nav>
