// apps/web/src/lib/components/SellWidget.svelte
<script lang="ts">
    import { createEventDispatcher } from "svelte";
    import CurrencyPlatformModal from "./CurrencyPlatformModal.svelte";

    // Form Data
    let amount = "";
    let counterparty = "";

    // Crypto Side State
    let selectedToken = { sym: "USDC", icon: "💲", network: "Base" };
    let selectedPlatform = { name: "Venmo", logo: "V" }; // Receiving Platform
    let selectedCurrency = { code: "USD", flag: "🇺🇸" };

    let isSubmitting = false;
    let step = "list"; // 'list' | 'form' | 'review'

    const dispatch = createEventDispatcher();

    function handleDepositSelect(asset: any) {
        selectedToken = asset;
        step = "form";
    }

    function handleReview() {
        if (!amount || !counterparty) return;
        step = "review";
    }

    function handleConfirm() {
        isSubmitting = true;

        // Dispatch signal intent
        dispatch("signal", {
            amount,
            mode: "sell",
            payingUsing: {
                platform: selectedPlatform,
                currency: selectedCurrency,
            },
            sellingAsset: { token: selectedToken },
            recipient: counterparty,
        });

        setTimeout(() => {
            isSubmitting = false;
        }, 500);
    }

    function handleCurrencySelect(e: any) {
        selectedCurrency = e.detail.currency;
        selectedPlatform = e.detail.platform;
        showCurrencyModal = false;
    }

    let showCurrencyModal = false;
</script>

<div
    class="swap-widget w-full max-w-[500px] mx-auto p-0 overflow-hidden relative group"
>
    <!-- Glow Effect -->
    <div
        class="absolute -bottom-20 -left-20 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl pointer-events-none group-hover:bg-purple-500/20 transition-all duration-700"
    ></div>

    <!-- Header -->
    <div class="p-6 pb-2 relative z-10 text-center">
        <h2
            class="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-400 mb-1"
        >
            Sell Crypto
        </h2>
        <p class="text-xs text-gray-500">Off-ramp assets to your bank.</p>
    </div>

    <!-- Content -->
    <div class="px-6 pb-8 space-y-5 relative z-10 pt-4">
        {#if step === "list"}
            <!-- Step 1: Asset Selection -->
            <div class="space-y-3">
                <div
                    class="flex items-center justify-between px-2 pb-2 border-b border-white/5"
                >
                    <span
                        class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >Select Asset to Sell</span
                    >
                </div>

                {#each [{ sym: "USDC", name: "USD Coin", icon: "💲", network: "Base" }, { sym: "ETH", name: "Ethereum", icon: "Ξ", network: "Base" }] as asset}
                    <button
                        on:click={() => handleDepositSelect(asset)}
                        class="w-full flex items-center justify-between bg-[#050505]/50 p-4 rounded-xl border border-white/5 hover:bg-white/5 transition-all group text-left"
                    >
                        <div class="flex items-center gap-3">
                            <div
                                class="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-xl"
                            >
                                {asset.icon}
                            </div>
                            <div>
                                <h4 class="text-white font-bold">
                                    {asset.sym}
                                </h4>
                                <p class="text-xs text-gray-500">
                                    {asset.network}
                                </p>
                            </div>
                        </div>
                        <div
                            class="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-gray-400 group-hover:bg-white/10 group-hover:text-white transition-colors"
                        >
                            →
                        </div>
                    </button>
                {/each}
            </div>
        {:else if step === "form"}
            <!-- Step 2: Input Form -->
            <button
                on:click={() => (step = "list")}
                class="flex items-center gap-1 text-xs text-gray-500 hover:text-white mb-2 transition-colors"
            >
                ← Back to Assets
            </button>

            <!-- Sell Card -->
            <div
                class="bg-[#050505]/50 border border-white/5 rounded-2xl p-4 space-y-4"
            >
                <div class="flex justify-between items-center">
                    <label class="text-xs font-medium text-gray-400"
                        >You Sell</label
                    >
                    <div
                        class="flex items-center gap-2 px-2 py-1 rounded-full bg-white/5 border border-white/5 text-xs text-gray-300"
                    >
                        {selectedToken.network} Network
                    </div>
                </div>

                <div class="flex items-center gap-4">
                    <input
                        bind:value={amount}
                        type="number"
                        placeholder="0.00"
                        class="bg-transparent text-4xl font-medium text-white placeholder-gray-700 outline-none w-full"
                    />
                    <div
                        class="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-xl border border-white/10"
                    >
                        <span class="text-xl">{selectedToken.icon}</span>
                        <span class="font-bold text-white"
                            >{selectedToken.sym}</span
                        >
                    </div>
                </div>
            </div>

            <!-- Receive Card -->
            <div class="relative">
                <div
                    class="absolute left-1/2 -top-3 -translate-x-1/2 w-8 h-8 bg-[#111] rounded-full border border-white/10 flex items-center justify-center text-gray-500 z-10"
                >
                    ↓
                </div>
                <!-- Platform Selection -->
                <button
                    on:click={() => (showCurrencyModal = true)}
                    class="w-full bg-[#050505]/50 border border-white/5 rounded-2xl p-4 pt-6 transition-all hover:bg-white/5 hover:border-white/10 text-left space-y-4"
                >
                    <div class="flex justify-between items-center">
                        <label class="text-xs font-medium text-gray-400"
                            >You Receive (Fiat)</label
                        >
                        <div
                            class="flex items-center gap-1 text-xs text-gray-500"
                        >
                            Change Platform ›
                        </div>
                    </div>

                    <div class="flex items-center justify-between">
                        <div class="text-2xl font-bold text-gray-500">
                            ≈ {amount || "0.00"}
                            {selectedCurrency.code}
                        </div>
                        <div class="flex items-center gap-2">
                            <div
                                class="w-8 h-8 rounded bg-white text-black flex items-center justify-center font-bold text-lg"
                            >
                                {selectedPlatform.logo}
                            </div>
                            <span class="text-white font-bold text-lg"
                                >{selectedPlatform.name}</span
                            >
                        </div>
                    </div>
                </button>
            </div>

            <!-- Recipient Details -->
            <div class="pt-2">
                <label
                    for="details-input"
                    class="text-xs font-medium text-gray-400 block mb-2 px-1"
                    >Your {selectedPlatform.name} Tag/Email</label
                >
                <input
                    id="details-input"
                    bind:value={counterparty}
                    type="text"
                    placeholder={`e.g. @username or email`}
                    class="w-full bg-[#050505]/50 border border-white/5 rounded-xl p-4 text-white placeholder-gray-600 outline-none focus:border-blue-500/50 transition-colors"
                />
            </div>

            <button
                on:click={handleReview}
                disabled={!amount || !counterparty}
                class="w-full btn-primary py-4 text-base rounded-xl mt-4 disabled:opacity-50 disabled:cursor-not-allowed"
            >
                Review Order
            </button>
        {:else if step === "review"}
            <!-- Step 3: Review -->
            <button
                on:click={() => (step = "form")}
                class="flex items-center gap-1 text-xs text-gray-500 hover:text-white mb-2 transition-colors"
            >
                ← Edit Order
            </button>

            <div
                class="bg-white/5 border border-white/10 rounded-2xl p-6 space-y-6"
            >
                <h3 class="text-lg font-bold text-white text-center">
                    Confirm Sell Order
                </h3>

                <div class="space-y-4">
                    <div class="flex justify-between items-center">
                        <span class="text-gray-400">Selling</span>
                        <span class="text-white font-bold text-lg"
                            >{amount} {selectedToken.sym}</span
                        >
                    </div>
                    <div class="flex justify-between items-center">
                        <span class="text-gray-400">Receiving</span>
                        <span class="text-white font-bold text-lg"
                            >≈ {amount} {selectedCurrency.code}</span
                        >
                    </div>
                    <div class="w-full h-px bg-white/10"></div>
                    <div class="flex justify-between items-center text-sm">
                        <span class="text-gray-400">Platform</span>
                        <div class="flex items-center gap-2">
                            <span class="text-white"
                                >{selectedPlatform.name}</span
                            >
                        </div>
                    </div>
                    <div class="flex justify-between items-center text-sm">
                        <span class="text-gray-400">Recipient ID</span>
                        <span class="text-blue-400 font-mono"
                            >{counterparty}</span
                        >
                    </div>
                </div>

                <div
                    class="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-3 flex gap-3"
                >
                    <span class="text-xl">⚠️</span>
                    <p class="text-xs text-yellow-200/80 leading-relaxed">
                        Funds will be escrowed on-chain in a Smart Contract. You
                        will verify payment receipt via TLSN proof to release
                        funds.
                    </p>
                </div>
            </div>

            <button
                on:click={handleConfirm}
                disabled={isSubmitting}
                class="w-full btn-primary py-4 text-base rounded-xl relative overflow-hidden"
            >
                {#if isSubmitting}
                    <span class="flex items-center justify-center gap-2">
                        <svg
                            class="animate-spin h-5 w-5 text-white"
                            viewBox="0 0 24 24"
                        >
                            <circle
                                class="opacity-25"
                                cx="12"
                                cy="12"
                                r="10"
                                stroke="currentColor"
                                stroke-width="4"
                            ></circle>
                            <path
                                class="opacity-75"
                                fill="currentColor"
                                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                            ></path>
                        </svg>
                        Sign & Escrow
                    </span>
                {:else}
                    Confirm & Signal Intent
                {/if}
            </button>
        {/if}
    </div>

    <!-- Modals -->
    {#if showCurrencyModal}
        <CurrencyPlatformModal
            on:close={() => (showCurrencyModal = false)}
            on:select={handleCurrencySelect}
        />
    {/if}
</div>

// components/SellWidget.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import {
    getRefundAddressHint,
    isValidRefundAddress,
    resolveIntentsAssetId,
} from "@/lib/services/asset-map";
import { getUsdPriceByAssetId } from "@/lib/services/intents-pricing";

interface SellWidgetProps {
    onDeposit: (data: any) => Promise<void>;
    isConnected: boolean;
    onConnect: () => Promise<void>;
    isConnecting: boolean;
    isV2FlowEnabled: boolean;
    accountId: string | null;
    walletBalanceNear: string | null;
    isBalanceLoading: boolean;
    onRefreshBalance: () => Promise<void>;
}

function formatBalance(nearAmount: string | null): string {
    if (!nearAmount) return "Unavailable";

    const value = Number(nearAmount);
    if (!Number.isFinite(value)) return `${nearAmount} NEAR`;
    if (value >= 1) return `${value.toFixed(2)} NEAR`;
    return `${value.toFixed(4)} NEAR`;
}

function shortAccountId(accountId: string | null): string {
    if (!accountId) return "Unknown";
    if (accountId.length <= 16) return accountId;
    return `${accountId.slice(0, 8)}...${accountId.slice(-6)}`;
}

function formatUsdValue(value: number): string {
    return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 2,
    }).format(value);
}

export default function SellWidget({
    onDeposit,
    isConnected,
    onConnect,
    isConnecting,
    isV2FlowEnabled,
    accountId,
    walletBalanceNear,
    isBalanceLoading,
    onRefreshBalance,
}: SellWidgetProps) {
    const [amount, setAmount] = useState("");
    const [selectedToken, setSelectedToken] = useState({
        sym: "BTC",
        name: "Bitcoin",
        icon: "₿",
        network: "Bitcoin",
    });
    const [selectedPlatform] = useState({ name: "Venmo", logo: "V" });
    const [selectedCurrency] = useState({ code: "USD", flag: "🇺🇸" });
    const [refundTo, setRefundTo] = useState("");
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [actionError, setActionError] = useState("");
    const [step, setStep] = useState<"list" | "form" | "review">("list");
    const [assetUsdPrice, setAssetUsdPrice] = useState<number | null>(null);
    const numericAmount = Number(amount);
    const hasValidAmount = Number.isFinite(numericAmount) && numericAmount > 0;
    const selectedAssetId = useMemo(
        () => resolveIntentsAssetId(selectedToken.sym),
        [selectedToken.sym],
    );

    useEffect(() => {
        let active = true;

        const loadPrice = async () => {
            try {
                const price = await getUsdPriceByAssetId(selectedAssetId, selectedToken.sym);
                if (active) setAssetUsdPrice(price);
            } catch (error) {
                console.error("SellWidget: failed to load token price", error);
                if (active) setAssetUsdPrice(null);
            }
        };

        void loadPrice();
        return () => {
            active = false;
        };
    }, [selectedAssetId, selectedToken.sym]);

    const estimatedFiat = useMemo(() => {
        if (!hasValidAmount || !assetUsdPrice) return null;
        return numericAmount * assetUsdPrice;
    }, [hasValidAmount, numericAmount, assetUsdPrice]);

    const assets = [
        { sym: "BTC", name: "Bitcoin", icon: "₿", network: "Bitcoin" },
        { sym: "ETH", name: "Ethereum", icon: "Ξ", network: "Ethereum" },
        { sym: "ZEC", name: "Zcash", icon: "🛡️", network: "Zcash" },
    ];

    const handleAssetSelect = (asset: typeof assets[0]) => {
        setSelectedToken(asset);
        setStep("form");
    };

    const handleReview = () => {
        if (!hasValidAmount) {
            setActionError("Enter a valid amount greater than 0.");
            return;
        }
        if (!isValidRefundAddress(selectedToken.sym, refundTo)) {
            setActionError(`Enter a valid ${selectedToken.sym} refund address before continuing.`);
            return;
        }
        setActionError("");
        setStep("review");
    };

    const handleConfirm = async () => {
        setIsSubmitting(true);
        setActionError("");

        try {
            const depositPromise = onDeposit({
                amount: amount.trim(),
                mode: "sell",
                asset: selectedToken.sym,
                assetId: selectedAssetId,
                chain: selectedToken.network,
                refundTo: refundTo.trim(),
                acceptingPayment: {
                    platform: selectedPlatform,
                    currency: selectedCurrency,
                },
                // txHash will be set by the parent after successful deposit
            });

            await Promise.race([
                depositPromise,
                new Promise((_, reject) => {
                    setTimeout(
                        () => reject(new Error("Deposit request timed out after 150 seconds. Please try again.")),
                        150000,
                    );
                }),
            ]);
        } catch (e) {
            console.error("Deposit widget error:", e);
            setActionError((e as Error).message || "Deposit failed");
        } finally {
            setIsSubmitting(false);
        }
    };

    const handlePrimaryAction = async () => {
        if (isSubmitting) return;

        if (!isConnected) {
            setActionError("");
            await onConnect();
            return;
        }

        await handleConfirm();
    };

    return (
        <div className="swap-widget w-full max-w-[500px] mx-auto p-0 overflow-hidden relative group">
            {/* Glow Effect */}
            <div className="absolute -top-20 -right-20 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl pointer-events-none group-hover:bg-purple-500/20 transition-all duration-700"></div>

            {/* Header */}
            <div className="p-6 pb-2 relative z-10 text-center">
                <h2 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-400 mb-1">
                    Sell Crypto
                </h2>
                <p className="text-xs text-gray-500">Off-ramp crypto to fiat instantly.</p>
            </div>

            {/* Content */}
            <div className="px-6 pb-8 space-y-5 relative z-10 pt-4">
                {step === "list" && (
                    <div className="space-y-3">
                        <div className="flex items-center justify-between px-2 pb-2 border-b border-white/5">
                            <span className="text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Select Asset to Sell
                            </span>
                        </div>

                        {assets.map((asset) => (
                            <button
                                key={asset.sym}
                                onClick={() => handleAssetSelect(asset)}
                                className="w-full flex items-center justify-between bg-[#050505]/50 p-4 rounded-xl border border-white/5 hover:bg-white/5 transition-all group text-left"
                            >
                                <div className="flex items-center gap-3">
                                    <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-xl">
                                        {asset.icon}
                                    </div>
                                    <div>
                                        <h4 className="text-white font-bold">{asset.sym}</h4>
                                        <p className="text-xs text-gray-500">{asset.network}</p>
                                    </div>
                                </div>
                                <div className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-gray-400 group-hover:bg-white/10 group-hover:text-white transition-colors">
                                    →
                                </div>
                            </button>
                        ))}
                    </div>
                )}

                {step === "form" && (
                    <>
                        <button
                            onClick={() => setStep("list")}
                            className="flex items-center gap-1 text-xs text-gray-500 hover:text-white mb-2 transition-colors"
                        >
                            ← Back to Assets
                        </button>

                        {/* Deposit Card */}
                        <div className="w-full bg-[#050505]/50 border border-white/5 rounded-2xl p-4 space-y-4">
                            <div className="flex justify-between items-center">
                                <label className="text-xs font-medium text-gray-400">
                                    You Deposit (Crypto)
                                </label>
                            </div>

                            <div className="flex items-center justify-between">
                                <input
                                    type="number"
                                    min="0"
                                    step="any"
                                    inputMode="decimal"
                                    value={amount}
                                    onChange={(e) => setAmount(e.target.value)}
                                    placeholder="0.00"
                                    className="bg-transparent text-3xl font-medium text-white placeholder-gray-700 outline-none w-full"
                                />
                                <div className="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-xl border border-white/10">
                                    <span className="text-xl">{selectedToken.icon}</span>
                                    <span className="font-bold text-white">{selectedToken.sym}</span>
                                </div>
                            </div>
                        </div>

                        <div className="w-full bg-[#050505]/50 border border-white/5 rounded-2xl p-4 space-y-2">
                            <label className="text-xs font-medium text-gray-400">
                                Refund Address ({selectedToken.sym})
                            </label>
                            <input
                                type="text"
                                value={refundTo}
                                onChange={(e) => setRefundTo(e.target.value)}
                                placeholder={getRefundAddressHint(selectedToken.sym)}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-white outline-none focus:border-purple-400/60"
                            />
                            <p className="text-xs text-gray-500">
                                Used by Near Intents if funding fails or is refunded.
                            </p>
                        </div>

                        {/* Receive Card */}
                        <div className="relative">
                            <div className="absolute left-1/2 -top-3 -translate-x-1/2 w-8 h-8 bg-[#111] rounded-full border border-white/10 flex items-center justify-center text-gray-500 z-10">
                                ↓
                            </div>

                            <div className="bg-[#050505]/50 border border-white/5 rounded-2xl p-4 pt-6 space-y-4">
                                <div className="flex justify-between items-center">
                                    <label className="text-xs font-medium text-gray-400">
                                        You Receive (Fiat)
                                    </label>
                                    <div className="flex items-center gap-2 px-2 py-1 rounded-full bg-white/5 border border-white/5 text-xs text-gray-300">
                                        via {selectedPlatform.name}
                                    </div>
                                </div>

                                <div className="flex items-center justify-between">
                                    <div className="text-2xl font-bold text-gray-500">
                                        {estimatedFiat === null
                                            ? `≈ -- ${selectedCurrency.code}`
                                            : `≈ ${formatUsdValue(estimatedFiat)}`}
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <div className="w-8 h-8 rounded bg-white text-black flex items-center justify-center font-bold text-lg">
                                            {selectedPlatform.logo}
                                        </div>
                                        <span className="text-white font-bold text-lg">
                                            {selectedPlatform.name}
                                        </span>
                                    </div>
                                </div>
                                <p className="text-xs text-gray-500">
                                    {assetUsdPrice
                                        ? `1 ${selectedToken.sym} ≈ ${formatUsdValue(assetUsdPrice)}`
                                        : "Price unavailable"}
                                </p>
                            </div>
                        </div>

                        <button
                            onClick={handleReview}
                            disabled={!hasValidAmount || !isValidRefundAddress(selectedToken.sym, refundTo)}
                            className="w-full btn-primary py-4 text-base rounded-xl mt-4 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            Review Deposit
                        </button>
                    </>
                )}

                {step === "review" && (
                    <>
                        <button
                            onClick={() => setStep("form")}
                            className="flex items-center gap-1 text-xs text-gray-500 hover:text-white mb-2 transition-colors"
                        >
                            ← Edit Deposit
                        </button>

                        <div className="bg-white/5 border border-white/10 rounded-2xl p-6 space-y-6">
                            <h3 className="text-lg font-bold text-white text-center">
                                Confirm Deposit
                            </h3>

                            <div className="space-y-4">
                                <div className="flex justify-between items-center">
                                    <span className="text-gray-400">Depositing</span>
                                    <span className="text-white font-bold text-lg">
                                        {amount} {selectedToken.sym}
                                    </span>
                                </div>
                                <div className="flex justify-between items-center">
                                    <span className="text-gray-400">Receiving</span>
                                    <span className="text-white font-bold text-lg">
                                        {estimatedFiat === null
                                            ? `≈ -- ${selectedCurrency.code}`
                                            : `≈ ${formatUsdValue(estimatedFiat)}`}
                                    </span>
                                </div>
                                <div className="w-full h-px bg-white/10"></div>
                                <div className="flex justify-between items-center text-sm">
                                    <span className="text-gray-400">Payment Via</span>
                                    <span className="text-white">{selectedPlatform.name}</span>
                                </div>
                                <div className="flex justify-between items-center text-sm">
                                    <span className="text-gray-400">Network</span>
                                    <span className="text-purple-400">{selectedToken.network}</span>
                                </div>
                                <div className="flex justify-between items-center text-sm">
                                    <span className="text-gray-400">Asset ID</span>
                                    <span className="text-white font-mono text-xs">
                                        {selectedAssetId}
                                    </span>
                                </div>
                                <div className="flex justify-between items-center text-sm">
                                    <span className="text-gray-400">Refund To</span>
                                    <span className="text-white font-mono text-xs truncate w-56 text-right">
                                        {refundTo || "Not set"}
                                    </span>
                                </div>
                            </div>

                            <div className="bg-purple-500/10 border border-purple-500/20 rounded-xl p-3 flex gap-3">
                                <span className="text-xl">ℹ️</span>
                                <p className="text-xs text-purple-200/80 leading-relaxed">
                                    {isV2FlowEnabled
                                        ? `You are creating a funding intent. Send ${selectedToken.sym} to the generated address before the deadline to activate your listing.`
                                        : `Your crypto will be deposited into the MPC vault. Buyers will match your order and pay you via ${selectedPlatform.name}.`}
                                </p>
                            </div>

                            {isConnected && (
                                <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-3 space-y-3">
                                    <div className="flex items-center justify-between text-xs">
                                        <span className="text-blue-200/80">Wallet</span>
                                        <span className="font-mono text-blue-100">{shortAccountId(accountId)}</span>
                                    </div>
                                    <div className="flex items-center justify-between text-xs">
                                        <span className="text-blue-200/80">NEAR Balance</span>
                                        <span className="text-blue-100">
                                            {isBalanceLoading ? "Loading..." : formatBalance(walletBalanceNear)}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-2 pt-1">
                                        <button
                                            type="button"
                                            onClick={() => void onRefreshBalance()}
                                            className="px-3 py-1.5 rounded-lg border border-white/15 bg-white/5 hover:bg-white/10 text-xs text-white transition-colors"
                                        >
                                            Refresh
                                        </button>
                                        <a
                                            href="https://faucet.testnet.near.org/"
                                            target="_blank"
                                            rel="noreferrer"
                                            className="px-3 py-1.5 rounded-lg border border-emerald-400/30 bg-emerald-500/10 hover:bg-emerald-500/20 text-xs text-emerald-200 transition-colors"
                                        >
                                            Fund Wallet
                                        </a>
                                    </div>
                                </div>
                            )}
                        </div>

                        <button
                            type="button"
                            onClick={() => void handlePrimaryAction()}
                            disabled={isSubmitting || isConnecting}
                            className={`w-full py-4 text-base rounded-xl relative overflow-hidden ${isConnected ? "btn-primary" : "bg-blue-600 hover:bg-blue-700 text-white"
                                } cursor-pointer disabled:cursor-not-allowed`}
                        >
                            {isSubmitting ? (
                                <span className="flex items-center justify-center gap-2">
                                    <svg
                                        className="animate-spin h-5 w-5 text-white"
                                        viewBox="0 0 24 24"
                                    >
                                        <circle
                                            className="opacity-25"
                                            cx="12"
                                            cy="12"
                                            r="10"
                                            stroke="currentColor"
                                            strokeWidth="4"
                                        ></circle>
                                        <path
                                            className="opacity-75"
                                            fill="currentColor"
                                            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                                        ></path>
                                    </svg>
                                    {isV2FlowEnabled ? "Creating Funding Intent..." : "Creating Deposit..."}
                                </span>
                            ) : (
                                isConnected
                                    ? (isV2FlowEnabled ? "Confirm & Create Funding Intent" : "Confirm & Create Deposit")
                                    : isConnecting
                                        ? "Connecting..."
                                        : "Connect NEAR Wallet to Continue"
                            )}
                        </button>

                        {actionError && (
                            <div className="p-3 mt-3 bg-red-500/20 border border-red-500/40 rounded-xl text-sm text-red-200">
                                {actionError}
                            </div>
                        )}
                    </>
                )}
            </div>
        </div>
    );
}
